### ISSUE TITLE
Replicated storage (F+1)

### ISSUE THREAD

**Issue by bennetyee** [oasislabs/oasis-core#1338]
Tracking Issue for Decentralized Storage

## Goals

Improve transaction performance via fault tolerant decentralized storage, separating compute nodes from storage nodes.

## Details

Separating storage/compute functionalities should improve performance. Given enough replicas, storage nodes can ack writes from compute nodes without doing fsyncdata(2) first, because when a sufficient number of storage nodes will (later, but soon) write to SSD/HDD, the compute node is assured that the data will be available despite potential crash faults.  This means that contracts can run at network + memory speeds rather than disk data transfer speeds.  (We trade off RPC latency for storage I/O latencies.)  VERIFY SSD speeds vs network.

For VerC MVP, we will operate the storage nodes and the interfaces can change, so the F+1 CAS design is probably easier to implement and will yield better performance.  Later iterations (VerE) can switch to FEC CAS to reduce storage overhead as needed.

Storage server lifetime is ∞ for VerD, and we will manually but transparently handle storage migration if we need to failover to another machine.

## Linked issues

Depends on epic #1583.

* [x] [Replicated storage design](https://github.com/oasislabs/ekiden/issues/925) 
* [x] [Add receipts to storage interface](https://github.com/oasislabs/ekiden/issues/1384)
* [x] [Design for sync between storage nodes](https://github.com/oasislabs/ekiden/issues/1714)
* [x] [Fully implement storage RFC 22](https://github.com/oasislabs/ekiden/issues/1742)
* [x] [Multiple storage nodes can register with the registry](https://github.com/oasislabs/ekiden/issues/1701)
* [x] [Compute worker replicates updates to storage committee](https://github.com/oasislabs/ekiden/issues/1702)
* [ ] [Storage client only waits for F+1 successful writes](https://github.com/oasislabs/ekiden/issues/1821)
* [x] [Implement GetDiff from RFC 61](https://github.com/oasislabs/ekiden/issues/1746)
* [x] [Storage checkpoints](https://github.com/oasislabs/ekiden/issues/1758)
* [x] [Storage nodes sync from other storage nodes](https://github.com/oasislabs/ekiden/issues/1747)
* [x] [Storage purge and garbage collection](https://github.com/oasislabs/ekiden/issues/1759)
