### ISSUE TITLE
SGX compute committees

### ISSUE THREAD

**Issue by bennetyee** [oasislabs/oasis-core#1367]
Fully support TEE-based (SGX) transactions as a choice in the network.

## Details

We should fully support TEE-based (SGX) committees, the BFT registry should allow registration of TEE-enabled nodes and the BFT roothash should validate that results are actually being computed in TEEs. We should be able to test hardware SGX as part of our CI process.

## Linked Issues

 - [x] [Support an SGX compute committee](https://github.com/oasislabs/ekiden/issues/135)
- [x] [sgx: Periodically re-attest with IAS](https://github.com/oasislabs/ekiden/issues/1561)
- [x] [E2E tests with multiple runtimes](https://github.com/oasislabs/ekiden/issues/1062) - 2d
- [ ] [Should TEE attestations etc be included with commitments in the block header](https://github.com/oasislabs/ekiden/issues/1426) 
- [x] [Roothash should validate commit attestation for TEE-enabled nodes](https://github.com/oasislabs/ekiden/issues/940)

Integration:
- [x] run compute committee only
  - cross-cluster communication [pr](https://github.com/oasislabs/private-ops/pull/748)
- [x] [Buidlkite SGX Agents](https://github.com/oasislabs/private-packer/issues/20)
- [ ] gateway support for accessing other runtimes [issue](https://github.com/oasislabs/runtime-ethereum/issues/469)
  - (unknown, possibly more than one task)
- [x] [benchmark cross-cluster testnet](https://github.com/oasislabs/private-ops/issues/800)
- [x] [figure out ibm node storage requirements](https://github.com/oasislabs/private-ops/issues/799)
- [x] [monitoring & logs for ibm clusters](https://github.com/oasislabs/private-ops/issues/802)
- [x] [Bootstrap: registering the sgx entity & runtime](https://github.com/oasislabs/private-ops/issues/840)
- [ ] setup production ibm cluster (https://github.com/oasislabs/private-ops/issues/662)
  - note: this one is pretty straightforward but should be done last, as it will require spawning another SGX machine therefore increasing the costs

Fidelity:
- tying runtime actions/output to attestation (the "tie") [issue](https://github.com/oasislabs/ekiden/issues/940)
- incorporating the tie into ledger [issue](https://github.com/oasislabs/ekiden/issues/940)
- validating the tie in...
  - validators [issue](https://github.com/oasislabs/ekiden/issues/940)
  - gateway (?)
  - web3c clients (?)
- make sure key manager adequately controls access [issue](https://github.com/oasislabs/ekiden/issues/1291)
  - (unknown, possibly many, many tasks)

Improvements:
- [ ] removing high-privilege workarounds
  - worker sandbox <-> aesmd [issue](https://github.com/oasislabs/ekiden/issues/1417)
  - container <-> device [issue](https://github.com/oasislabs/private-ops/issues/795)
  -  Figure out if Intel SGX breaks sandbox isolation (oasislabs/ekiden#1433)
- [x] continuous delivery of compute committee in sync with compatible rest-of-the-network [issue](https://github.com/oasislabs/private-ops/issues/796)
- [ ] [scan for crosscluster nodeport access](https://github.com/oasislabs/private-ops/issues/786)
- [x] [ibmcloud ks cluster-config --export workaround](https://github.com/oasislabs/private-ops/issues/782)

Actual production-ness:
- [ ] production IAS credentials [issue](https://github.com/oasislabs/private-issues/issues/293)
- [ ] non-debug launch authorization [issue](https://github.com/oasislabs/private-issues/issues/122)
- [ ] write policy on acceptable attestations [issue (repurposed)](https://github.com/oasislabs/ekiden/issues/131)
 - More goes here
