### ISSUE TITLE
Storage servers space reclamation

### ISSUE THREAD

**Issue by bennetyee** [oasislabs/oasis-core#1379]
Storage servers space reclamation tracking issue

## Details

Storage servers enter into contract with the network to store data for some period of time.  Our current storage design uses an immutable data store interface using CAS.  When the data is contract state and the state mutates, the keys (hash of contents) change, and old data in the CAS KV store becomes unreachable.  We should have a mechanism to allow storage servers to reclaim this storage, e.g., via garbage collection.

Unless the storage server knows the structure of the data stored in the h(V) ->V storage, it does not know what blobs are unreachable from the current root hash.

## Linked Issues

* [ ] Co-design of Merklized storage data structure and CAS storage
* [ ] Design of GC mechanism / APIs
* [ ] Modify storage servers to enable reclamation

**Comment by kostko** [comment]
Done as part of #1759.
