### ISSUE TITLE
Staking needs to interact with the rest of the system

### ISSUE THREAD

**Issue by Yawning** [oasislabs/oasis-core#1877]
This somewhat overlaps with a number of existing staking issues, but the design has changed somewhat, and there is a distinction to be drawn between policy design (TBD), and the engineering work to support implementing whatever policy is decided upon (this issue).

 * [ ] Wire the staking backend into the registry (#311).
   * [x] Figure out how we want to handle staking thresholds.
      * [x] Staking thresholds (to qualify) should be parameters (Runtime configurable).
   * [x] Stake required to register entities.
   * [x] Stake required to register nodes (#310).
   * [ ] Stake required to be a validator.
   * [x] Validators need to have registry entries.
 * [ ] Wire the staking backend into the scheduler
   * [ ] Scheduler should pick validators based on stake.
   * [x] Scheduler should pick nodes based on stake (#1980).
   * [x] Debonding period (may just be controlled by the scheduler, ~period dependent on class of node~).
   * [ ] Scheduler should manage validators(?).
     * [ ] Flexible validator staking requirements (top N stake gets votes vs random, weighted voting vs fixed).
 * [ ] Add a way to suspend transfers. (Independent of #1860).

*Estimated cost: No idea, depends on what the new deployment process looks like.*

**Comment by kostko** [comment]
I believe this was done.
