### ISSUE TITLE
More comprehensive storage tests

### ISSUE THREAD

**Issue by kostko** [oasislabs/oasis-core#1888]
We should check which cases of the data structure and sync protocol are not covered and add tests for them.

Some known issues for which tests should be added and the issues should be fixed:
* [ ] There is an issue where in some cases the returned write log contains entries which are the same as the values that were already present prior to the write. This can happen if you set a key to the same value to which it was set before. We should update tests and fix this to reduce the size of the write log in this case.
* [x] `GetSubtree` is currently broken if called with a non-zero start depth (this is not currently ever used in the tree implementations, but should be fixed and a test should be added).
* [x] Make sure we have tests for `derefNodeID`
  * [x] Dereferencing the root node.
  * [x] Dereferencing a node where `bitDepth + n.LabelBitLength == id.BitDepth + 1` (and other off by one cases).
* [x] Make sure that we have all the pruning cases covered.
