### ISSUE TITLE
Clean up structures and protocols

### ISSUE THREAD

**Issue by kostko** [oasislabs/oasis-core#1893]
Tracking issue for cleaning up legacy cruft from data structures and RPC protocols.

## Linked issues

* [x] [Clean up go/common/node](https://github.com/oasislabs/ekiden/issues/1892)
* [x] [Sort out the RPC s11n situation](https://github.com/oasislabs/ekiden/issues/809)
* [x] [Clean up the registry API](https://github.com/oasislabs/ekiden/issues/1947)
* [x] [Make sure all backend getters take a block height argument](https://github.com/oasislabs/ekiden/issues/2001)
* [ ] Trim down the exposed interfaces.
* [x] Try Really Hard(TM) to remove the "deferred InitChain" kludge.

*Estimated cost: <1 sprint*
