### ISSUE TITLE
Enable runtime registrations

### ISSUE THREAD

**Issue by kostko** [oasislabs/oasis-core#2406]
Currently runtime registrations are disabled, we should make sure that anyone can register a runtime, subject to certain provisions like paying gas fees and maybe also depositing stake in escrow.

## Linked Issues
* [x] [Properly allocate runtime IDs](https://github.com/oasislabs/oasis-core/issues/1693)
* [x] [Compute runtime's key manager should be checked](https://github.com/oasislabs/oasis-core/issues/2459)
* [ ] [Make sure we can scale to lots of runtimes](https://github.com/oasislabs/oasis-core/issues/2349)
* [x] Consensus fee model for runtimes
* [x] Allow anyone to register a runtime
* [x] Suspend runtimes which cannot pay housekeeping fees
* [x] [Compute nodes should set fees for consensus transactions](https://github.com/oasislabs/oasis-core/issues/2521)
* [x] [Add key manager policy document submission](https://github.com/oasislabs/oasis-core/issues/2516)
* [x] [Allow anyone to register a key manager](https://github.com/oasislabs/oasis-core/issues/2445)
* [x] [Flexible key manager policy signers](https://github.com/oasislabs/oasis-core/issues/2444)
* [x] [Remove granular role registration](https://github.com/oasislabs/oasis-core/issues/2107)
* [x] [Runtime node admission policies](https://github.com/oasislabs/oasis-core/issues/2513)
* [x] [runtime: Stop hardcoding runtime IDs into enclave binaries](https://github.com/oasislabs/oasis-core/issues/2519)
* [x] [Registering a runtime should require a deposit](https://github.com/oasislabs/oasis-core/issues/2638)
* [x] Enable runtime registrations by default (invert/rename the consensus parameter).

*Estimated cost: 3 sprints*
