### ISSUE TITLE
Initial consensus upgrade mechanism

### ISSUE THREAD

**Issue by kostko** [oasislabs/oasis-core#2446]
This initial version of the consensus upgrade mechanism would require manual agreement on upgrade descriptors and manual fetching of new binaries:
* No on-chain coordination.
* Schedule upgrade on old binary via node controller interface by specifying the upgrade descriptor.
* The upgrade descriptor is persisted and the upgrade is scheduled.
* When the epoch specified in the upgrade descriptor ends, the old binary halts. If restarted, the old binary will still remain halted (unique name of the upgrade is used as a check whether the current binary implements the required upgrade).
* Binary is replaced and the new binary is started.
* Before consensus starts, the persistent upgrade descriptor is checked and the migration code is executed, making the required state changes.
* Upgrade descriptor is cleared (or archived) and the consensus process is resumed with the new binary running.

The mechanism should be independent of the consensus layer backend.

## Linked Issues
* [x] [Node controller interface to schedule upgrade](https://github.com/oasislabs/oasis-core/issues/2465)
* [x] [Binary halts after scheduled upgrade](https://github.com/oasislabs/oasis-core/issues/2466)
* [x] [Migration handlers for upgrading consensus state](https://github.com/oasislabs/oasis-core/issues/2467)

*Estimated cost: 2 sprints*
